version: '3'

services:
  app:
    build: .
    restart: always
    # container_name: 
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code/
      - ./log/gunicorn:/log
    ports:
      - "8080:8000"
    environment:
      - PGSQL_HOST=db
      - PGSQL_PORT=5432
      - PGSQL_DB=${PGSQL_DB}
      - PGSQL_USER=${PGSQL_USER}
      - PGSQL_PWD=${PGSQL_PWD}
    networks:
      - backend

  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${PGSQL_DB}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PWD}
    ports:
      - ${PGSQL_PORT}:5432
    networks:
      - backend

  redis:
    image: redis
    restart: always

networks:
  backend:

volumes:
  data:
